### ISSUE TITLE
Bug in example workflow

### ISSUE THREAD

**Issue by d-walsh** [All-Hands-AI/openhands-resolver#171]
The workflow is not valid. .github/workflows/openhands-resolver.yml (Line: 8, Col: 3): Error calling workflow 'All-Hands-AI/openhands-resolver/.github/workflows/openhands-resolver.yml@main'. The workflow is requesting 'contents: write, issues: write, pull-requests: write', but is only allowed 'contents: read, issues: none, pull-requests: none'

**Comment by neubig** [comment]
Hi! Could you make sure that you followed step 4 here and gave the right permissions?

https://github.com/All-Hands-AI/openhands-resolver?tab=readme-ov-file#using-the-github-actions-workflow

**Comment by neubig** [comment]
Yeah, unfortunately that doesn't work because we're using a personal access token to make the commits (not the `GITHUB_TOKEN` provided by the workflow directly). I wasn't able to figure out how to make the commits with `GITHUB_TOKEN`, but if anyone figures out a way to do that I'd be happy to have a PR. Anyway, I'll close this for now!
