### ISSUE TITLE
Feature: add the ability to @openhands-agents within PR/Issue

### ISSUE THREAD

**Issue by xingyaoww** [All-Hands-AI/openhands-resolver#202]
I'm hoping for a way to simply @openhands-agent inside a PR with an instruction accompanying it, and it will automatically start an openhands-resolver that has access to the history conversations & git changes, and start to respond to my instruction there.

Not sure if we need to create a Github App this way?

**Comment by malhotra5** [comment]
This sounds interesting! Would be willing to help collaborate on this feature. Quick question - currently openhands-resolver will resolve review comments inside a PR. Openhands considers the entire history within the comment thread.

Would this issue solve the two following problems?

1. Having openhands-resolver only consider review comments with "@openhands-agent" instead of every review comment?
2. Include better agent context with git changes?

**Comment by xingyaoww** [comment]
> Openhands considers the entire history within the comment thread.

Yeah, i hope when @openhands-agent is tagged, the entire history of the PR/issue up until the most recent @ will be included as input to the agent, including all the git changes the agent has made so far (i.e., a view of git diff against the PR and base).

Basically i'd hope we can easily brings the agent into an existing conversation and let it go from there

**Comment by xingyaoww** [comment]
For showing git changes, maybe we can do something similar to this:

https://github.com/All-Hands-AI/OpenHands/blob/2e50a5bef55796ad03b72cfc096956d02caa7f20/openhands/events/observation/files.py#L86-L122

**Comment by neubig** [comment]
Hey @xingyaoww , just to confirm: is there a reason why you'd prefer this rather than adding the "fix-me" label to the issue?

The difficulty in tagging @openhands-agent is that some people might not be using @openhands-agent at all, if they use a different personal access token on their own private repository.

**Comment by xingyaoww** [comment]
@neubig I think this just feel a little bit more "human"-like experience: tagging a friend of something to look at your stuff. Could we work around that by creating a Github app though?

**Comment by neubig** [comment]
Yeah, I think this may be blocked by #155 , so maybe we can just leave a comment there and close this issue?

**Comment by xingyaoww** [comment]
Sounds good!

**Comment by xingyaoww** [comment]
Close this for now
